"""add Executor model

Revision ID: 13ef5630719a
Revises: 8dfc33f64c4f
Create Date: 2024-09-13 19:13:08.704192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13ef5630719a'
down_revision: Union[str, None] = '8dfc33f64c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('miner_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('miner_port', sa.Integer(), nullable=False),
    sa.Column('miner_hotkey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_id', sa.Uuid(), nullable=False),
    sa.Column('executor_ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_ssh_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_ssh_port', sa.Integer(), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.JSON()), nullable=False),
    sa.Column('private_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rented', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executor_id'), 'executor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executor_id'), table_name='executor')
    op.drop_table('executor')
    # ### end Alembic commands ###
