"""add sshkey model

Revision ID: 33af87c19aab
Revises: be7476c8c0ee
Create Date: 2024-09-19 09:37:04.395391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '33af87c19aab'
down_revision: Union[str, None] = 'be7476c8c0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sshkey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sshkey_id'), 'sshkey', ['id'], unique=False)
    op.create_index(op.f('ix_sshkey_user_id'), 'sshkey', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sshkey_user_id'), table_name='sshkey')
    op.drop_index(op.f('ix_sshkey_id'), table_name='sshkey')
    op.drop_table('sshkey')
    # ### end Alembic commands ###
