"""add template table

Revision ID: 689d4e4b7985
Revises: 13ef5630719a
Create Date: 2024-09-17 11:19:21.996298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '689d4e4b7985'
down_revision: Union[str, None] = '13ef5630719a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_type', sa.Enum('serverless', 'pod', name='templatetype'), nullable=True),
    sa.Column('compute_type', sa.Enum('nvidia_gpu', 'amd_gpu', 'cpu', name='templatecomputetype'), nullable=True),
    sa.Column('container_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('container_start_command', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('volume_mount_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_visibility', sa.Enum('public', 'private', name='templatevisibility'), nullable=True),
    sa.Column('environment_variables', postgresql.JSONB(astext_type=sa.JSON()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_index(op.f('ix_template_is_deleted'), 'template', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_is_deleted'), table_name='template')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
