"""Update executor table

Revision ID: 73ed84612528
Revises: 13ef5630719a
Create Date: 2024-09-17 08:08:13.506779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '73ed84612528'
down_revision: Union[str, None] = '13ef5630719a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('validator_hotkey', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('executor', sa.Column('executor_ip_port', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('executor', 'executor_ssh_port')
    op.drop_column('executor', 'executor_ssh_username')
    op.drop_column('executor', 'public_key')
    op.drop_column('executor', 'miner_port')
    op.drop_column('executor', 'miner_address')
    op.drop_column('executor', 'private_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('private_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('executor', sa.Column('miner_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('executor', sa.Column('miner_port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('executor', sa.Column('public_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('executor', sa.Column('executor_ssh_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('executor', sa.Column('executor_ssh_port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('executor', 'executor_ip_port')
    op.drop_column('executor', 'validator_hotkey')
    # ### end Alembic commands ###
