"""Add Pod model

Revision ID: be7476c8c0ee
Revises: ac1953fa1c5e
Create Date: 2024-09-18 10:30:51.034610

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be7476c8c0ee"
down_revision: str | None = "ac1953fa1c5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pod",
        sa.Column("executor_id", sa.Uuid(), nullable=False),
        sa.Column("container_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("volume_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ports_mapping", postgresql.JSONB(astext_type=sa.JSON()), nullable=False),
        sa.ForeignKeyConstraint(
            ["executor_id"],
            ["executor.id"],
        ),
        sa.PrimaryKeyConstraint("executor_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pod")
    # ### end Alembic commands ###
