"""add pod model

Revision ID: f9c42a646799
Revises: 689d4e4b7985
Create Date: 2024-09-17 12:05:53.507106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9c42a646799'
down_revision: Union[str, None] = '689d4e4b7985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('running', 'stopped', name='podstatus'), nullable=True),
    sa.Column('type', sa.Enum('cpu', 'gpu', name='podtype'), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('executor_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('template_config', postgresql.JSONB(astext_type=sa.JSON()), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=True),
    sa.Column('isinstance_pricing', postgresql.JSONB(astext_type=sa.JSON()), nullable=True),
    sa.Column('container_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portMaps', postgresql.JSONB(astext_type=sa.JSON()), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['executor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_executor_id'), 'pod', ['executor_id'], unique=False)
    op.create_index(op.f('ix_pod_id'), 'pod', ['id'], unique=False)
    op.create_index(op.f('ix_pod_template_id'), 'pod', ['template_id'], unique=False)
    op.create_index(op.f('ix_pod_user_id'), 'pod', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pod_user_id'), table_name='pod')
    op.drop_index(op.f('ix_pod_template_id'), table_name='pod')
    op.drop_index(op.f('ix_pod_id'), table_name='pod')
    op.drop_index(op.f('ix_pod_executor_id'), table_name='pod')
    op.drop_table('pod')
    # ### end Alembic commands ###
